# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Household clustering
tagline:          'A Jekyll theme'
description:      'Group people and products based on their intrinsec relations.'
#baseurl:          '/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Jerome Luscher, Yann Mentha, Daniel Pacheco Gutierrez, Raphaël Reis Nunes'
  # url:            https://twitter.com/fongandrewc

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

remote_theme: fongandrew/hydeout

# Sidebar link settings
sidebar_home_link:  true
#sidebar_blog_link:  '/story'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
